# The parts of libgcc needed for C++ exception handling: the ARM EABI
# unwinder, compiled as -fPIC so it can be linked into the plugin .so.
# The toolchain's own libgcc.a is not compiled with -fPIC, so its unwinder
# objects cannot be linked into a shared object (they would produce dynamic
# relocations the MetaModule loader does not support).
#
# The file list matches what libgcc's t-bpabi puts in LIB2ADDEH for
# arm-none-eabi targets.

set(libgcc ${CMAKE_CURRENT_LIST_DIR}/libgcc)

set(LIBGCC_EH_SOURCES
	${CMAKE_CURRENT_LIST_DIR}/glue/unwind-arm.c # libgcc's unwind-arm.c + __gnu_Unwind_Find_exidx
	${libgcc}/config/arm/libunwind.S
	${libgcc}/config/arm/pr-support.c
	${libgcc}/unwind-c.c
	${CMAKE_CURRENT_LIST_DIR}/glue/vterminate_lite.cc
)

target_sources(metamodule-plugin-libc PRIVATE
	${LIBGCC_EH_SOURCES}
)

# glue/ carries stubs for headers normally generated by the libgcc build
# system (tconfig.h, tsystem.h, auto-target.h). libgcc/ provides
# unwind-arm-common.inc and unwind-pe.h (the latter is also needed by
# libsupc++'s eh_personality.cc).
target_include_directories(metamodule-plugin-libc PRIVATE
	${CMAKE_CURRENT_LIST_DIR}/glue
	${libgcc}
)

# Match how libgcc compiles its LIB2ADDEH objects.
# -Wno-address: the unwinder tests the address of the weak
# __gnu_Unwind_Find_exidx, which is always true now that we define it in the
# same translation unit.
set_source_files_properties(
	${CMAKE_CURRENT_LIST_DIR}/glue/unwind-arm.c
	${libgcc}/config/arm/pr-support.c
	${libgcc}/unwind-c.c
	PROPERTIES COMPILE_OPTIONS "-fexceptions;-fnon-call-exceptions;-Wno-address"
)
